{
  imports = [
    ./alexsmobs.nix
    ./amendments.nix
    ./anotherfurniture.nix
    ./appleskin.nix
    ./architectury.nix
    ./attributefix.nix
    ./balm.nix
    ./bclib.nix
    ./bellsandwhistles.nix
    ./betterdays.nix
    ./betterend.nix
    ./betternether.nix
    ./bookshelf.nix
    ./c2me.nix
    ./chipped.nix
    ./citadel.nix
    ./clothconfig.nix
    ./clumps.nix
    ./cmparallelpipes.nix
    ./copycats.nix
    ./create.nix
    ./createaddition.nix
    ./createbb.nix
    ./createcompatiblestorage.nix
    ./createconfectionery1211.nix
    ./createcopperandzinc.nix
    ./createdeco.nix
    ./createdragonsplus.nix
    ./createdynlight.nix
    ./createencased.nix
    ./createenchantmentindustry.nix
    ./createfactory.nix
    ./createfood.nix
    ./createframed.nix
    ./creategoggles.nix
    ./createltab.nix
    ./createnewage.nix
    ./createnuclear.nix
    ./createnumismatics.nix
    ./createpowerloader.nix
    ./createrailwaysnavigator.nix
    ./createthreadedtrains.nix
    ./createtrackmap.nix
    ./createultimatefactory.nix
    ./createvibrantvaults.nix
    ./creativecore.nix
    ./designndecor.nix
    ./distanthorizons.nix
    ./dragonlib.nix
    ./dynamictrees.nix
    ./dynamictreesplus.nix
    ./escalated.nix
    ./farmersdelight.nix
    ./ferritecore.nix
    ./gaboulibs.nix
    ./garnished.nix
    ./geckolib.nix
    ./glitchcore.nix
    ./gravestone.nix
    ./interiors.nix
    ./jade.nix
    ./jei.nix
    ./journeymap.nix
    ./kotlinforforge.nix
    ./lithium.nix
    ./lithostitched.nix
    ./mca.nix
    ./mcwdoors.nix
    ./mcwfurniture.nix
    ./mcwmcwfences.nix
    ./mcwmcwwindows.nix
    ./midnightlib.nix
    ./modernfix.nix
    ./moonlight.nix
    ./neoforgeversionsereneseasonsplus.nix
    ./netherportalfix.nix
    ./nochatreports.nix
    ./notenoughcrashes.nix
    ./packetfixer.nix
    ./pantographsandwires.nix
    ./polymorph.nix
    ./powergrid.nix
    ./prickle.nix
    ./railways.nix
    ./rechiseled.nix
    ./rechiseledcreate.nix
    ./resourcefullib.nix
    ./sereneseasons.nix
    ./shulkerboxtooltip.nix
    ./simplesnowyfix.nix
    ./sliceanddice.nix
    ./sophisticatedbackpacks.nix
    ./sophisticatedbackpackscreateintegration.nix
    ./sophisticatedcore.nix
    ./sophisticatedstorage.nix
    ./sophisticatedstoragecreateintegration.nix
    ./soundphysicsremastered.nix
    ./spark.nix
    ./supermartijn642configlib.nix
    ./supermartijn642corelib.nix
    ./supplementaries.nix
    ./tectonic.nix
    ./trainutilities.nix
    ./worldweaver.nix
    ./wunderlib.nix
    ./yungsapi.nix
    ./yungsbetterdungeons.nix
    ./yungsbetterendisland.nix
    ./yungsbettermineshafts.nix
    ./yungsbetternetherfortresses.nix
    ./yungsextras.nix
  ];
}
